name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - run: echo "Triggered by ${{ github.event_name }} event."

    - name: Check out repository code ${{ github.repository }} on ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Installing dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
    - run: yarn test